--
-- Create table T_CHAT_MESSAGE
--
CREATE TABLE T_CHAT_MESSAGE (
  ID DECIMAL(18,0),
  TIMESTAMP TIMESTAMP,
	NICK VARCHAR(20),
	ROOM VARCHAR(30),
	MESSAGE VARCHAR(2000),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ID_CHAT_MESSAGE START WITH 1000000 INCREMENT BY 10;
